stages:
  - test

test:
  image: ubuntu:latest
  services:
    - docker:19.03.0-dind
  stage: test
  variables:
    MONGO_NON_ROOT_ROLE: $MONGO_NON_ROOT_ROLE
    MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
    MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
    MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update
    - apt-get install -yq software-properties-common python3-software-properties wget apt-transport-https ca-certificates curl
    - add-apt-repository -y ppa:deadsnakes/ppa
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - apt-get update
    - apt-get -yq install python3.6 docker-ce
    - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
    - wget https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - python -m pip install --upgrade pip
    - if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - docker-compose -f docker-compose.yml build --no-cache
    - docker-compose -f docker-compose.yml up -d
  script:
    - python -m venv .venv
    - . .venv/bin/activate
    - tox -e py36
