---
apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: restaurant
type: Opaque
data:
  root_password: ZXhhbXBsZQ==
  api_password: dGVzdA==
  #MONGO_URI_DEV: mongodb://igz:test@restaurant-db-service:27017/restaurant
  MONGO_URI_DEV: bW9uZ29kYjovL2lnejp0ZXN0QHJlc3RhdXJhbnQtZGItc2VydmljZToyNzAxNy9yZXN0YXVyYW50

