# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.4, 3.5, 3.6]
        toxenv: [db]
        mongodb-version: [4.2]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace sensitive content with secrets
      run: |
        sudo apt update
        sudo apt install -y gettext
        envsubst < tox.ini.tpl > tox.ini

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

    - name: Test with tox
      run: tox
